dbt_milkyway:
  outputs:
    dev:
      dataset: sessions  
      job_execution_timeout_seconds: 3600
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: repeatable-analyses   
      threads: 4
      type: bigquery
  target: dev
